"""
Meson build file generation for the Devana build system.

Generates meson.build files for the project and individual components.
"""

import logging
from pathlib import Path
from typing import List
from datetime import datetime

from .components import Component
from .config import ProductConfig

logger = logging.getLogger(__name__)


def generate_main_meson_build(
    components: List[Component],
    idl_files: List[Path],
    product_config: ProductConfig,
    output_path: Path
):
    root_dir = output_path.parent

    meson_content = f"""# Auto-generated by Devana Build System
# DO NOT EDIT MANUALLY - Changes will be overwritten
# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

project('{product_config.name}', 'cpp',
  version : '{product_config.version}',
  default_options : [
    'cpp_std={product_config.cpp_standard}',
    'buildtype={product_config.default_buildtype}',
    'warning_level=2',
    'werror=false',
    'b_ndebug=if-release'
  ],
  meson_version : '{product_config.meson_version}'
)

qt6 = import('qt6')
fs = import('fs')

qt6_dep = dependency('qt6',
  modules : {product_config.qt6_modules},
  required : true
)

"""

    if product_config.openssl_required:
        meson_content += "openssl_dep = dependency('openssl', required : true)\n\n"
    else:
        meson_content += "openssl_dep = dependency('openssl', required : false)\n\n"

    if product_config.idl_enabled and idl_files:
        meson_content += f"idl_compiler = find_program('{product_config.idl_compiler}')\n\nidl_files = [\n"
        for idl in idl_files:
            meson_content += f"  '{idl.relative_to(root_dir)}',\n"
        meson_content += """]\n
generated_topic_headers = []
foreach idl_file : idl_files
  topic_name = fs.stem(idl_file)
  gen_header = custom_target(
    'generate_topic_' + topic_name,
    input: idl_file,
    output: topic_name + '.h',
    command: [idl_compiler, '@INPUT@', '-o', '@OUTPUT@'],
    install: false,
  )
  generated_topic_headers += gen_header
endforeach

topics_dep = declare_dependency(sources: generated_topic_headers)

"""
    else:
        meson_content += "generated_topic_headers = []\ntopics_dep = declare_dependency()\n\n"

    meson_content += "inc_dirs = include_directories('src'"
    for comp in components:
        meson_content += f",\n  '{comp.path.relative_to(root_dir)}'"
    meson_content += "\n)\n\ncomponent_deps = []\n\n"

    for comp in components:
        dep_var = f"{comp.name.replace('-', '_')}_dep"
        meson_content += f"subdir('{comp.path.relative_to(root_dir)}')\ncomponent_deps += {dep_var}\n\n"

    meson_content += f"""executable('{product_config.output_name}',
  'src/app/main.cpp',
  dependencies : [qt6_dep] + component_deps,
  include_directories : inc_dirs,
  install : true,
  install_dir : 'bin'
)

summary({{
  'Product': '{product_config.display_name}',
  'Version': '{product_config.version}',
  'Qt6 support': qt6_dep.found(),
  'OpenSSL support': openssl_dep.found(),
  'Components': component_deps.length(),
  'IDL topics': {len(idl_files)},
  'Build type': get_option('buildtype'),
  'C++ standard': '{product_config.cpp_standard}'
}}, section: 'Configuration')
"""

    output_path.write_text(meson_content)
    logger.info(f"Generated meson.build with {len(components)} components")


def generate_component_meson_build(comp: Component):
    if not comp.sources:
        meson_file = comp.path / "meson.build"
        meson_file.write_text(
            f"# meson.build for {comp.name}\n"
            f"{comp.name}_dep = declare_dependency(include_directories : include_directories('.'))\n"
        )
        return

    meson_content = f"# meson.build for {comp.name}\n\n{comp.name}_sources = files(\n"
    for src in sorted(comp.sources):
        meson_content += f"  '{src.relative_to(comp.path)}',\n"
    meson_content += ")\n\n"

    if comp.has_qt:
        meson_content += f"{comp.name}_moc_files = qt6.preprocess(\n"
        moc_headers = [h for h in comp.headers if 'Q_OBJECT' in h.read_text(errors='ignore')]
        if moc_headers:
            meson_content += "  moc_headers : [\n"
            for h in moc_headers:
                meson_content += f"    '{h.relative_to(comp.path)}',\n"
            meson_content += "  ],\n"
        if comp.ui_files:
            meson_content += "  ui_files : [\n"
            for ui in comp.ui_files:
                meson_content += f"    '{ui.relative_to(comp.path)}',\n"
            meson_content += "  ],\n"
        if comp.qrc_files:
            meson_content += "  qresources : [\n"
            for qrc in comp.qrc_files:
                meson_content += f"    '{qrc.relative_to(comp.path)}',\n"
            meson_content += "  ],\n"
        meson_content += f"  dependencies : qt6_dep\n)\n\n{comp.name}_sources += {comp.name}_moc_files\n\n"

    deps = "[qt6_dep, topics_dep]" if comp.has_qt else "[topics_dep]"
    meson_content += (
        f"{comp.name}_lib = static_library('{comp.name}',\n"
        f"  {comp.name}_sources,\n"
        f"  dependencies : {deps},\n"
        f"  include_directories : inc_dirs\n)\n\n"
        f"{comp.name}_dep = declare_dependency(\n"
        f"  link_with : {comp.name}_lib,\n"
        f"  include_directories : include_directories('.')\n)\n"
    )

    (comp.path / "meson.build").write_text(meson_content)
